#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy
script:
    - curl http://169.254.169.254/
# You can append own scripts after this line

