#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy
before_script:
    - sudo iptables -L
script:
    - curl http://169.254.169.254/0.1/meta-data/
# You can append own scripts after this line

